=== chetmurthy/utjson/schema-overrides/schema-draft-v4.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Modified JSON Schema draft v4 that includes the optional '$ref' and 'format'",
    "$id": "#TheType",
    "utj:annotation": "[object]",
    "definitions": {
        "schemaArray": {
            "type": "array",
	    "utj:annotation": "[array]",
            "minItems": 1,
            "items": { "$ref": "#TheType" }
        },
        "positiveInteger": {
            "type": "integer",
            "minimum": 0
        },
        "positiveIntegerDefault0": {
            "allOf": [ { "$ref": "#/definitions/positiveInteger" }, { "default": 0 } ]
        },
        "simpleTypes": {
            "enum": [ "array", "boolean", "integer", "null", "number", "object", "string" ]
        },
        "stringArray": {
            "type": "array",
            "items": { "type": "string" },
            "minItems": 1,
            "uniqueItems": true
        },
	"properties_title": {
	    "$ref": "#/properties/title"
	},
	"properties_default": {
	    "$ref": "#/properties/default"
	},
	"properties_description": {
	    "$ref": "#/properties/description"
	},
	"properties_enum": {
	    "$ref": "#/properties/enum"
	},
	"properties_exclusiveMaximum": {
	    "$ref": "#/properties/exclusiveMaximum"
	},
	"properties_exclusiveMinimum": {
	    "$ref": "#/properties/exclusiveMinimum"
	},
	"properties_maximum": {
	    "$ref": "#/properties/maximum"
	},
	"properties_minimum": {
	    "$ref": "#/properties/minimum"
	},
	"properties_multipleOf": {
	    "$ref": "#/properties/multipleOf"
	},
	"properties_pattern": {
	    "$ref": "#/properties/pattern"
	},
	"properties_uniqueItems": {
	    "$ref": "#/properties/uniqueItems"
	},
	"properties_type": {
	    "$ref": "#/properties/type"
	}
    },
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        },
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "$ref": {
            "type": "string"
        },
        "format": {
            "type": "string"
        },
        "title": {
	    "$id": "#/properties/title",
            "type": "string"
        },
        "description": {
	    "$id": "#/properties/description",
            "type": "string"
        },
        "default": {
	    "$id": "#/properties/default"
	},
        "multipleOf": {
	    "$id": "#/properties/multipleOf",
            "type": "number",
            "exclusiveMinimum": 0
        },
        "maximum": {
	    "$id": "#/properties/maximum",
            "type": "number"
        },
        "exclusiveMaximum": {
	    "$id": "#/properties/exclusiveMaximum",
            "type": "boolean",
            "default": false
        },
        "minimum": {
	    "$id": "#/properties/minimum",
            "type": "number"
        },
        "exclusiveMinimum": {
	    "$id": "#/properties/exclusiveMinimum",
            "type": "boolean",
            "default": false
        },
        "maxLength": { "$ref": "#/definitions/positiveInteger" },
        "minLength": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "pattern": {
	    "$id": "#/properties/pattern",
            "type": "string",
            "format": "regex"
        },
        "additionalItems": {
            "anyOf": [
                { "type": "boolean" },
                { "$ref": "#TheType" }
            ],
            "default": { }
        },
        "items": {
            "anyOf": [
                { "$ref": "#TheType" },
                { "$ref": "#/definitions/schemaArray" }
            ],
            "default": { }
        },
        "maxItems": { "$ref": "#/definitions/positiveInteger" },
        "minItems": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "uniqueItems": {
	    "$id": "#/properties/uniqueItems",
            "type": "boolean",
            "default": false
        },
        "maxProperties": { "$ref": "#/definitions/positiveInteger" },
        "minProperties": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "required": { "$ref": "#/definitions/stringArray" },
        "additionalProperties": {
            "anyOf": [
                { "type": "boolean" },
                { "$ref": "#TheType" }
            ],
            "default": { }
        },
        "definitions": {
            "type": "object",
            "additionalProperties": { "$ref": "#TheType" },
            "default": { }
        },
        "properties": {
            "type": "object",
            "additionalProperties": { "$ref": "#TheType" },
            "default": { }
        },
        "patternProperties": {
            "type": "object",
            "additionalProperties": { "$ref": "#TheType" },
            "default": { }
        },
        "dependencies": {
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    { "$ref": "#TheType" },
                    { "$ref": "#/definitions/stringArray" }
                ]
            }
        },
        "enum": {
	    "$id": "#/properties/enum",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true
        },
        "type": {
	    "$id": "#/properties/type",
            "anyOf": [
                { "$ref": "#/definitions/simpleTypes" },
                {
                    "type": "array",
                    "items": { "$ref": "#/definitions/simpleTypes" },
                    "minItems": 1,
                    "uniqueItems": true
                }
            ]
        },
        "allOf": { "$ref": "#/definitions/schemaArray" },
        "anyOf": { "$ref": "#/definitions/schemaArray" },
        "oneOf": { "$ref": "#/definitions/schemaArray" },
        "not": { "$ref": "#TheType" }
    },
    "dependencies": {
        "exclusiveMaximum": [ "maximum" ],
        "exclusiveMinimum": [ "minimum" ]
    },
    "default": { }
}

=== chetmurthy/utjson/schema-overrides/FIXED-schema/resjson.json
{

    "title": "JSON schema for Windows resource files (.resjson)",
    "$schema": "http://json-schema.org/draft-04/schema#",

    "type": "object",
    "minProperties": 1,
    "additionalProperties": {
        "anyOf": [
            {
                "type": "string"
            },
            {
                "$ref": "#/definitions/resource"
            }
        ]
    },
    "definitions": {
        "resource": {
	    "utj:annotation": "[sealed,object]",
            "type": "object",
            "additionalProperties": {
                "minProperties": 1,
                "anyOf": [
                    {
                        "type": "string"
                    },
                    {
                        "$ref": "#/definitions/resource"
                    }
                ]
            }
        }
    }
}
